// Generated by gencpp from file lab5_pkg/captureResponse.msg
// DO NOT EDIT!


#ifndef LAB5_PKG_MESSAGE_CAPTURERESPONSE_H
#define LAB5_PKG_MESSAGE_CAPTURERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab5_pkg
{
template <class ContainerAllocator>
struct captureResponse_
{
  typedef captureResponse_<ContainerAllocator> Type;

  captureResponse_()
    : success(false)  {
    }
  captureResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::lab5_pkg::captureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5_pkg::captureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct captureResponse_

typedef ::lab5_pkg::captureResponse_<std::allocator<void> > captureResponse;

typedef boost::shared_ptr< ::lab5_pkg::captureResponse > captureResponsePtr;
typedef boost::shared_ptr< ::lab5_pkg::captureResponse const> captureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab5_pkg::captureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab5_pkg::captureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab5_pkg::captureResponse_<ContainerAllocator1> & lhs, const ::lab5_pkg::captureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab5_pkg::captureResponse_<ContainerAllocator1> & lhs, const ::lab5_pkg::captureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab5_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lab5_pkg::captureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab5_pkg::captureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_pkg::captureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_pkg::captureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_pkg::captureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_pkg::captureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab5_pkg::captureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::lab5_pkg::captureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5_pkg::captureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab5_pkg/captureResponse";
  }

  static const char* value(const ::lab5_pkg::captureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab5_pkg::captureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::lab5_pkg::captureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab5_pkg::captureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct captureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5_pkg::captureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab5_pkg::captureResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB5_PKG_MESSAGE_CAPTURERESPONSE_H
